### PR TITLE
[PAGES] index.html: minor changes

### PR DESCRIPTION
**Pull request by 0x5c**
- Changed section 'videos' to 'project'
- Added 'original idea' link to Node's site (n-o-d-e.net)

### CODE REVIEW

**Comment by Ne02ptzero** [comment]
LGTM 👍

**Comment by 0x5c** [comment]
@Ne02ptzero The slack is down, would it be possible to go to discord?

**Comment by JetseVerschuren** [comment]
What do you mean with "The slack is down"?

**Comment by 0x5c** [comment]
This https://status.slack.com, plus the fact that I'm unable to connect.

**Comment by JetseVerschuren** [comment]
Slack is working for me.

**Comment by 0x5c** [comment]
The only part of slack that is working for me is the notification from the github bot in #n2n-protocols

**Comment by JetseVerschuren** [comment]
Yeah your right. For me to.

**Comment by 0x5c** [comment]
I seems to be able to connect to slack now

**Pull request merged**
