### PR TITLE
Grammar and stuffs

### PR DESCRIPTION
**Pull request by 64BitUniverse**

### CODE REVIEW

**Comment by jnms-me** [comment]
Looks good.

**Comment by 0x5c** [comment]
@Reavershark
The problem is that the file does not exist anymore, since a long time ago (before the switch to `groff`, commit:  03d8c0f )

**Comment by jnms-me** [comment]
Oh i see. Not too much to go trough.

**Comment by 0x5c** [comment]
Changes need to be made manually to the current code.

**Comment by Ne02ptzero** [comment]
Closing, see #18 and 9eda0949664713099b143774c4be2175e5851bb9 for more information.

**Pull request closed without merging**
